---
kind: pipeline
type: docker
name: Julia 1.2 - linux - amd64
platform:
  os: linux
  arch: amd64
steps:
  - name: Tests
    image: julia:1.2
    commands:
      - julia --project=@. -e '
          using Pkg;
          Pkg.instantiate();
          Pkg.build();
          Pkg.test();'
